security/basicapp/urls.py
from django.urls import path
from . import views


app_name = 'basicapp'

urlpatterns = [
	     path('',views.index,name='index'),
	     path('register/',views.register,name='register'),
	     path('login/',views.user_login,name='user_login'),
	     path('logout/',views.user_logout,name='user_logout'),
			  
			  ]

security/security/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
	path('',include('basicapp.urls')),
	path('',include('basicapp.urls')),
    path('admin/', admin.site.urls),
]

security/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE)
	
	protfolio_site = models.URLField(blank=True)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
	
	def __str__(self):
		return self.user.username

security/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())
	
	class Meta():
		model = User
		fields = ('username','email','password')
	
class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model = UserProfileInfo
		fields = ('protfolio_site','profile_pic')

security/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm,UserProfileInfoForm

#Imports for form_login method of Login page

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout


# Create your views here.


def index(request):
	return render(request,'basicapp/index.html')

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('basicapp:index'))


def user_login(request):
	
	if request.method =='POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		
        #Checking and  matching the password
		user = authenticate(username=username,password=password)
		if user:
			
			if user.is_active:
				
				login(request,user)
				return HttpResponseRedirect(reverse('basicapp:index'))
			else:
				return HttpResponse("Account not Active")
		else:
			print(f"Login Failed! Username = {username} and Password ={password}")
			return HttpResponse("Invalid username or password")
	else:
		return render(request,'basicapp/login.html')


def register(request):
	
	registered = False
	
	if request.method == 'POST':
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileInfoForm(data=request.POST)
		
		if user_form.is_valid() and profile_form.is_valid():
			
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			
			profile = profile_form.save(commit=False)
			profile.user = user
			
			if 'profile_pic' in request.FILES:
				profile.profile_pic = request.FILES['profile_pic']
			
			profile.save()
			
			registered = True
			
		else:
			print(user_form.errors,profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = UserProfileInfoForm()
		
	return render(request,'basicapp/register.html',{
		'user_form':user_form, 'profile_form':profile_form,'registered':registered
	})
		

security/templates/basicapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Working on Users Security</title>
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	
</head>
<body>
<nav>
	<ul>
		<li><a href="{% url 'basicapp:index'%}">Index</a></li>
		<li><a href="{% url 'basicapp:register'%}">Register</a></li>
		
		{% if user.is_authenticated %}
		<li><a href="{% url 'basicapp:user_logout' %}">Logout</a></li>
		{% else %}
		
		<li><a href="{% url 'basicapp:user_login' %}">Login</a></li>
		
		{% endif %}
	</ul>
	{% block body_block %}
	
	{% endblock %}
	
</nav>
	
</body>
</html>

security/templates/basicapp/index.html
{% extends 'basicapp/base.html' %}

{% block body_block %}
<h1>Django Index Page</h1>
	
	{% endblock %}

security/templates/basicapp/login.html
{% extends 'basicapp/base.html' %}


{% block body_block %}

<h1>Login Page</h1>

<form action="{% url 'basicapp:user_login' %}" method="post">
	{% csrf_token %}
	
	<input type="text" name="username">
	<input type="password" name="password">
	
	
	
	<input type="submit" value="Login">
	
	
	
</form>
	
	{% endblock %}

security/templates/basicapp/register.html
{% extends 'basicapp/base.html' %}
{% block body_block %}

<h1>Registration Page !</h1>

		{% if registered %}
		 <h2>Thank you for Registering!</h2>

		{% else %}
		  <h1>Register Here !</h1>
		  <h2>Fill the form!!</h2>


		  <form action="" method='post' enctype="multipart/form-data" >

			  {% csrf_token %}
			  {{user_form.as_p}}
			  {{profile_form.as_p}}
			  <input type="submit" value="Register">


		  </form>

		{% endif %}
    
    
	{% endblock %}